services:
  movies-notifications-api:
    build:
      context: src/
      dockerfile: Dockerfile
    depends_on:
      - movies-rabbitmq
    volumes:
      - ./src:/code
    env_file:
      - ./.env
#    restart: always
    networks:
      - movies_network
      - elk_stack

  nginx-notifications-api:
    image: nginx:1.19.2
    depends_on:
      - movies-notifications-api
      - movies-rabbitmq
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/
#    restart: always
    networks:
      - movies_network
      - elk_stack

  notify-grpc:
    build:
      context: src/
      dockerfile: Dockerfile.grpc
    env_file:
      - ./.env
    volumes:
      - ./src:/code
    networks:
      - movies_network
      - elk_stack
    depends_on:
#      - movies-notifications-api
      - movies-rabbitmq

  movies-notifications-scheduler:
    build:
      context: scheduler/
      dockerfile: Dockerfile
    command: python3 /code/scheduler.py
    depends_on:
      - movies-rabbitmq
    volumes:
      - ./worker:/code
    env_file:
      - ./.env
    networks:
      - elk_stack
      - movies_network

  movies-notifications-worker:
    build:
      context: worker/
      dockerfile: Dockerfile
    command: python3 /code/worker.py
    volumes:
      - ./worker:/code
    env_file:
      - ./.env
    depends_on:
      - movies-notifications-api
      - movies-notifications-scheduler
      - movies-rabbitmq
    networks:
      - elk_stack
      - movies_network

  movies-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - elk_stack
      - movies_network

  filebeat-notifications-api:
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - movies-notifications-api
      - nginx-notifications-api
      - movies-rabbitmq
    networks:
      - elk_stack
      - movies_network


networks:
  elk_stack:
    external: true
  movies_network:
    external: true
    name: movies_network
